# Generated by Django 5.0.6 on 2024-05-21 12:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='usertoken',
            index=models.Index(fields=['user'], name='account_use_user_id_4894e5_idx'),
        ),
        migrations.AddIndex(
            model_name='usertoken',
            index=models.Index(fields=['token'], name='account_use_token_077e19_idx'),
        ),
        migrations.AddIndex(
            model_name='usertoken',
            index=models.Index(fields=['expiration_date'], name='account_use_expirat_a2c2d4_idx'),
        ),
        migrations.AddIndex(
            model_name='usertoken',
            index=models.Index(fields=['used'], name='account_use_used_4f0fe0_idx'),
        ),
        migrations.AddIndex(
            model_name='usertoken',
            index=models.Index(fields=['expired'], name='account_use_expired_99e877_idx'),
        ),
    ]
