version: '3'

services:

    app:
        build: .
        env_file: .env
        container_name: cms
        ports:
            - "8000:8000"
        volumes:
            - static-data:/static
        depends_on:
            - pgpool

    pgpool:
        image: edoburu/pgbouncer:latest
        container_name: pgbouncer
        restart: always
        ports:
            - "6432:6432"
        environment:
            - DATABASE_URL=postgres://postgres:postgres-password@10.88.0.4:5432/crm_db
        volumes:
            - ./script/pgbouncer/pgbouncer.ini:/etc/pgbouncer/pgbouncer.ini
            - ./script/pgbouncer/userlist.txt:/etc/pgbouncer/userlist.txt

volumes:
    static-data: 